import os

# Avoid BLAS oversubscription when using joblib.
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eigh
from scipy.ndimage import gaussian_filter1d
from joblib import Parallel, delayed

# ============================================================
# Fast symmetry-resolved ED for the integrable TFIM, hz = 0
#
# H = J sum_i sz_i sz_{i+1} + hx sum_i sx_i
# V = sum_i sx_i = dH/dhx
#
# Resolved exactly:
#   - translation momentum q = 0, ..., N-1
#   - global spin-flip parity p = +/-1, P = prod_i sx_i
#
# Reflection is not resolved explicitly. In a fixed momentum sector it is
# only an internal symmetry for q=0 and, for even N, q=N/2. The optional
# clean_degenerate_subspaces step removes residual omega=0 basis artifacts
# from any remaining exact degeneracies.
# ============================================================


def translate_left(s, N):
    mask = (1 << N) - 1
    return ((s << 1) & mask) | (s >> (N - 1))


def spin_flip(s, N):
    return s ^ ((1 << N) - 1)


def diagonal_energy_zz(s, N, J):
    e = 0.0
    for i in range(N):
        zi = 1 if ((s >> i) & 1) else -1
        zj = 1 if ((s >> ((i + 1) % N)) & 1) else -1
        e += J * zi * zj
    return e


def group_images_from_rep(rep, N):
    """Return the 2N images T^r P^f |rep>, with possible duplicates."""
    images = []
    x0 = rep
    x1 = spin_flip(rep, N)
    for r in range(N):
        images.append((x0, r, 0))
        images.append((x1, r, 1))
        x0 = translate_left(x0, N)
        x1 = translate_left(x1, N)
    return images


def build_translation_parity_orbits(N):
    """
    Build canonical representatives under the Abelian group generated by
    translation T and global spin flip P.

    For every computational basis state s, returns a representative rep_of[s]
    and a group element (shift_of[s], flip_of[s]) such that

        s = T**shift_of[s] P**flip_of[s] rep_of[s].

    If there are multiple such group elements because of a stabilizer, an
    arbitrary one is stored. For non-vanishing projected basis states, the
    sector character is trivial on the stabilizer, so the choice is harmless.
    """
    D = 1 << N
    seen = np.zeros(D, dtype=bool)
    rep_of = np.empty(D, dtype=np.int64)
    shift_of = np.empty(D, dtype=np.int16)
    flip_of = np.empty(D, dtype=np.int8)
    reps = []

    for s in range(D):
        if seen[s]:
            continue

        # First find the canonical minimum in the full T x P orbit.
        raw = group_images_from_rep(s, N)
        rep = min(x for x, _, _ in raw)
        reps.append(rep)

        # Now populate using images generated from the canonical rep.
        for x, r, f in group_images_from_rep(rep, N):
            if not seen[x]:
                seen[x] = True
                rep_of[x] = rep
                shift_of[x] = r
                flip_of[x] = f

    return reps, rep_of, shift_of, flip_of


def projected_norm_for_rep(rep, N, q, parity, tol=1e-12):
    """
    Norm of the unnormalized projected vector

        |u> = sum_{r=0}^{N-1} exp(-ikr) [T^r |rep> + parity T^r P |rep>].

    Returns zero if the projection vanishes in the chosen (q, parity) sector.
    """
    k = 2.0 * np.pi * q / N
    coeffs = {}

    x0 = rep
    x1 = spin_flip(rep, N)
    for r in range(N):
        phase = np.exp(-1j * k * r)
        coeffs[x0] = coeffs.get(x0, 0.0j) + phase
        coeffs[x1] = coeffs.get(x1, 0.0j) + parity * phase
        x0 = translate_left(x0, N)
        x1 = translate_left(x1, N)

    norm = float(np.sum(np.abs(list(coeffs.values())) ** 2))
    if norm < tol:
        return 0.0
    return norm


def allowed_reps_for_sector(N, q, parity, group_reps):
    reps = []
    norms = {}
    for rep in group_reps:
        norm = projected_norm_for_rep(rep, N, q, parity)
        if norm > 0.0:
            reps.append(rep)
            norms[rep] = norm
    return reps, norms


def build_Hz_and_V_sector(N, q, parity, J, hx, group_reps, rep_of, shift_of, flip_of):
    """
    Build H and V directly in one (momentum, spin-flip parity) sector.

    Direct matrix-element formula:

        <b;k,p| V |a;k,p>
        = sqrt(norm_b / norm_a) sum_i exp(i k shift_i) p**flip_i,

    where sigma_i^x |rep_a> = T**shift_i P**flip_i |rep_b>.
    """
    k = 2.0 * np.pi * q / N
    sector_reps, norms = allowed_reps_for_sector(N, q, parity, group_reps)
    dim = len(sector_reps)

    if dim == 0:
        return None

    index = {rep: a for a, rep in enumerate(sector_reps)}

    Hz = np.zeros((dim, dim), dtype=np.complex128)
    V = np.zeros((dim, dim), dtype=np.complex128)

    for a, rep_a in enumerate(sector_reps):
        Hz[a, a] = diagonal_energy_zz(rep_a, N, J)
        norm_a = norms[rep_a]

        for i in range(N):
            y = rep_a ^ (1 << i)
            rep_b = int(rep_of[y])
            b = index.get(rep_b)
            if b is None:
                continue

            norm_b = norms[rep_b]
            shift = int(shift_of[y])
            f = int(flip_of[y])

            chi = np.exp(1j * k * shift) * (parity if f else 1.0)
            V[b, a] += np.sqrt(norm_b / norm_a) * chi

    # Clean roundoff and enforce Hermiticity.
    Hz = 0.5 * (Hz + Hz.conj().T)
    V = 0.5 * (V + V.conj().T)
    Hz[np.abs(Hz) < 1e-14] = 0.0
    V[np.abs(V) < 1e-14] = 0.0

    H = Hz + hx * V
    H = 0.5 * (H + H.conj().T)
    H[np.abs(H) < 1e-14] = 0.0

    return H, V, sector_reps, norms


def diagonalize_V_inside_degenerate_H_subspaces(E, VE, energy_tol=1e-10):
    """
    Remove basis arbitrariness inside exactly/nearly degenerate H subspaces by
    diagonalizing V within each such subspace.
    """
    VE = VE.copy()
    dim = len(E)
    start = 0

    while start < dim:
        stop = start + 1
        while stop < dim and abs(E[stop] - E[start]) <= energy_tol:
            stop += 1

        if stop - start > 1:
            sl = slice(start, stop)
            _, W = eigh(0.5 * (VE[sl, sl] + VE[sl, sl].conj().T))
            VE[sl, :] = W.conj().T @ VE[sl, :]
            VE[:, sl] = VE[:, sl] @ W

        start = stop

    VE = 0.5 * (VE + VE.conj().T)
    VE[np.abs(VE) < 1e-14] = 0.0
    return VE


def diagonalize_sector(N, q, parity, J, hx, group_reps, rep_of, shift_of, flip_of,
                       clean_degenerate_subspaces=True, energy_tol=1e-10):
    built = build_Hz_and_V_sector(N, q, parity, J, hx, group_reps, rep_of, shift_of, flip_of)
    if built is None:
        return None

    H, V, sector_reps, norms = built
    E, U = eigh(H)
    VE = U.conj().T @ V @ U
    VE = 0.5 * (VE + VE.conj().T)

    if clean_degenerate_subspaces:
        VE = diagonalize_V_inside_degenerate_H_subspaces(E, VE, energy_tol=energy_tol)

    return {
        "q": q,
        "parity": parity,
        "E": E,
        "VE": VE,
        "dim": len(E),
    }


def make_frequency_grid(omega_max, n_omega):
    omega = np.linspace(-omega_max, omega_max, n_omega)
    d_omega = omega[1] - omega[0]
    edges = np.empty(n_omega + 1)
    edges[1:-1] = 0.5 * (omega[:-1] + omega[1:])
    edges[0] = omega[0] - 0.5 * d_omega
    edges[-1] = omega[-1] + 0.5 * d_omega
    return omega, edges, d_omega


def accumulate_sector_histogram(sector, omega_edges, beta, Emin, Z, Vmean,
                                drop_diagonal_delta=True,
                                drop_near_zero_delta=False,
                                zero_tol=1e-12,
                                block_size=256):
    E = sector["E"]
    VE = sector["VE"]
    dim = len(E)
    hist = np.zeros(len(omega_edges) - 1, dtype=np.float64)

    p = np.exp(-beta * (E - Emin))

    Vc = VE.copy()
    diag = np.diag(Vc).copy()
    np.fill_diagonal(Vc, diag - Vmean)

    if drop_diagonal_delta:
        np.fill_diagonal(Vc, 0.0)

    absV2 = np.abs(Vc) ** 2

    for m0 in range(0, dim, block_size):
        m1 = min(m0 + block_size, dim)
        dE = E[None, :] - E[m0:m1, None]
        pm = p[m0:m1, None]
        pn = p[None, :]
        weights = (np.pi / Z) * (pm + pn) * absV2[m0:m1, :]

        dE_flat = dE.ravel()
        w_flat = weights.ravel()
        keep = w_flat > 1e-28
        if drop_near_zero_delta:
            keep &= np.abs(dE_flat) > zero_tol

        if np.any(keep):
            h, _ = np.histogram(dE_flat[keep], bins=omega_edges, weights=w_flat[keep])
            hist += h

    return hist


def connected_symmetrized_spectral_function_TFIM_fast_symmetry_resolved(
    N,
    J,
    hx,
    beta=0.0,
    eta=0.05,
    n_omega=2001,
    omega_max=None,
    drop_diagonal_delta=True,
    drop_near_zero_delta=False,
    zero_tol=1e-12,
    clean_degenerate_subspaces=True,
    energy_tol=1e-10,
    per_site=True,
    n_jobs=-1,
    block_size=256,
    verbose=10,
):
    """
    Connected symmetrized spectral function of V=sum_i sx_i for the integrable
    TFIM with hz=0, resolving translation and global spin-flip parity.

    Convention:

        S_sym(omega) = pi/Z sum_mn (p_m+p_n) |<m|V_c|n>|^2
                       delta(omega - (E_n-E_m)).
    """
    D = 1 << N
    print(f"Building T x P orbits for N={N}, D={D}...")
    group_reps, rep_of, shift_of, flip_of = build_translation_parity_orbits(N)
    print(f"Number of T x P orbits: {len(group_reps)}")

    print("Diagonalizing (momentum, spin-flip parity) sectors...")
    sector_args = [(q, p) for q in range(N) for p in (+1, -1)]
    sectors = Parallel(n_jobs=n_jobs, backend="loky", verbose=verbose)(
        delayed(diagonalize_sector)(
            N, q, p, J, hx, group_reps, rep_of, shift_of, flip_of,
            clean_degenerate_subspaces, energy_tol
        )
        for q, p in sector_args
    )
    sectors = [s for s in sectors if s is not None]

    all_E = np.concatenate([s["E"] for s in sectors])
    Emin = float(np.min(all_E))
    Emax = float(np.max(all_E))
    bandwidth = Emax - Emin
    if omega_max is None:
        omega_max = bandwidth
    omega, omega_edges, d_omega = make_frequency_grid(omega_max, n_omega)

    Z = 0.0
    Vmean_num = 0.0
    for s in sectors:
        E = s["E"]
        VE = s["VE"]
        p = np.exp(-beta * (E - Emin))
        Z += np.sum(p)
        Vmean_num += np.sum(p * np.real(np.diag(VE)))
    Vmean = Vmean_num / Z

    print(f"Total Hilbert dimension check: {sum(s['dim'] for s in sectors)}")
    print(f"Emin = {Emin:.12g}, Emax = {Emax:.12g}, bandwidth = {bandwidth:.12g}")
    print(f"Shifted partition function Z = {Z:.12g}")
    print(f"<V> = {Vmean:.12g}")

    print("Accumulating spectral weights...")
    hist_parts = Parallel(n_jobs=n_jobs, backend="loky", verbose=verbose)(
        delayed(accumulate_sector_histogram)(
            s, omega_edges, beta, Emin, Z, Vmean,
            drop_diagonal_delta, drop_near_zero_delta, zero_tol, block_size
        )
        for s in sectors
    )
    hist = np.sum(hist_parts, axis=0)

    sigma_bins = eta / d_omega
    S = gaussian_filter1d(hist, sigma=sigma_bins, mode="constant") / d_omega
    if per_site:
        S = S / N

    info = {
        "N": N,
        "Hilbert_dimension": D,
        "num_TxP_orbits": len(group_reps),
        "sector_dimensions": {(s["q"], s["parity"]): s["dim"] for s in sectors},
        "J": J,
        "hx": hx,
        "beta": beta,
        "eta": eta,
        "omega_max": omega_max,
        "n_omega": n_omega,
        "d_omega": d_omega,
        "Emin": Emin,
        "Emax": Emax,
        "bandwidth": bandwidth,
        "Z_shifted": Z,
        "Vmean": Vmean,
        "drop_diagonal_delta": drop_diagonal_delta,
        "drop_near_zero_delta": drop_near_zero_delta,
        "zero_tol": zero_tol,
        "clean_degenerate_subspaces": clean_degenerate_subspaces,
        "energy_tol": energy_tol,
        "per_site": per_site,
        "n_jobs": n_jobs,
        "block_size": block_size,
    }
    return omega, S, info


# Short alias.
connected_symmetrized_spectral_function = (
    connected_symmetrized_spectral_function_TFIM_fast_symmetry_resolved
)


if __name__ == "__main__":
    N = 17
    J = 1.0
    hx = 1.05
    beta = 0.01

    omega, S, info = connected_symmetrized_spectral_function(
        N=N,
        J=J,
        hx=hx,
        beta=beta,
        eta=0.005,
        n_omega=4001,
        omega_max=None,
        drop_diagonal_delta=True,
        drop_near_zero_delta=True,
        zero_tol=1e-10,
        clean_degenerate_subspaces=True,
        energy_tol=1e-10,
        per_site=True,
        n_jobs=8,
        block_size=256,
        verbose=10,
    )

    print("\nDiagnostics:")
    for key, val in info.items():
        if key != "sector_dimensions":
            print(f"{key}: {val}")

    out = np.column_stack([omega, S])
    np.savetxt(
        f"./../data/spectralFnED_N{N}_J{J:.6f}_hx{hx:.6f}_hz{0.0:.6f}_beta{beta:.6f}.csv",
        out,
        delimiter=",",
        header="omega,S_connected_symmetrized",
        comments="",
    )

    mask = omega > 0
    plt.figure()
    plt.plot(omega[mask], S[mask], lw=1.5)
    plt.xlabel(r"$\omega$")
    plt.ylabel(r"$S_{\rm sym}^{\rm conn}(\omega)/N$")
    plt.xscale("log")
    plt.yscale("log")
    plt.tight_layout()
    plt.show()
